---

  - name: Download Check_mk Paket
    get_url:
      url: https://mathias-kettner.de/support/{{ check_mk_version }}/check-mk-raw-{{ check_mk_version }}-el7-65.x86_64.rpm
      dest: /tmp/check-mk-raw-{{ check_mk_version }}-el7-65.x86_64.rpm
      validate_certs: no
      mode: 0755
  
  - name: Install Check_mk rpm
    yum:
      name: /tmp/check-mk-raw-{{ check_mk_version }}-el7-65.x86_64.rpm
      state: present

  - name: confirure livestatus port in Firewall 
    firewalld:
      port: "{{ livestatus_port }}/tcp"
      service: http
      permanent: true
      state: enabled
    
  - name: list omd sites
    command: omd sites
    register: myomdsites

  - name: create new omd sites
    command: omd create "{{ omdsite }}"
    when: vars['omdsite'] not in myomdsites.stdout
    
  - name: Copy the configuration file 
    template: 
      src: site.j2 
      dest: /opt/omd/sites/{{ omdsite }}/etc/omd/site.conf
      force: yes
      owner: "{{ omdsite }}"
      group: "{{ omdsite }}"
      mode: '0655'
    notify: 
    - restart omd
