---
- hosts: centos
  remote_user: root
  roles: 
#  - { role: blackstar257.selinux, selinux_state: disabled }
#  - { role: goozbach.EPEL, epel_testing_enabled: 1 }
#   - { role: peru.proxy_settings, tags: ['proxy'] }

  tasks:
  - name: notwendige tools installieren
    yum: state=latest name={{ item }}
    with_items:
    - epel-release
    - bash-completion
    - bash-completion-extras
    - mc
    - setroubleshoot-server
    - vim
