---
- hosts: server
  remote_user: root
  # roles:
  #- opdavies.webmin
  
  tasks:
  - name: notwendige tools installieren
    yum: state=present name={{ item }}
    with_items: 
    - bash-completion
    - mc
