---
- hosts: server
  remote_user: root
  roles:
  #- opdavies.webmin
   - { role: blackstar257.selinux, selinux_state: disabled }
   - { role: goozbach.EPEL, epel_testing_enabled: 1 }
   
  tasks:
  - name: notwendige tools installieren
    yum: state=present name={{ item }}
    with_items: 
    - bash-completion
    - mc
    - setroubleshoot-server
