---
- hosts: server
  remote_user: root
  roles:
# - opdavies.webmin
  - { role: sfromm.postgresql }
    
  tasks:
  - name: notwendige tools installieren
    yum: state=present name={{ item }}
    with_items: 
    - zlib-devel 
    - bzip2-devel 
    - openssl 
    - openssl-devel 
    - ncurses-devel 
    - sqlite-devel 
    - readline-devel 
    - tk-devel 
    - gdbm-devel 
    - libpcap-devel 
    - xz-devel 
    - git 
    - libpng 
    - libjpeg 
    - libXext 
    - curl 
    - xorg-x11-font-utils 
    - fontconfig 
    - python-virtualenv 
    - libevent-devel 
    - libxml2-devel 
    - libxslt-devel 
    - openldap-devel 
    - openjpeg-devel 
    - freetype-devel 
    - libjpeg-turbo-devel 
    - libtiff-devel 
    - kernel-devel 
    - wkhtmltopdf
    - python-pip
    
  - name: DB User anlegen
    expect:
      command: createuser --createdb --username postgres --no-createrole --no-superuser --pwprompt {{ dbuser }}
      become: yes
      become_user: postgres
      responses:
      Question:
        - {{ dbuser_pw }}
        - {{ dbuser_pw }}
    
#  - name: odoo per github installieren 
#    command:  git clone https://www.github.com/odoo/odoo --depth 1 --branch 8.0 --single-branch  

