---
- hosts: server
  remote_user: root
  roles:
  - { role: sfromm.postgresql }
#  - { role: bennojoy.openldap_server }
    
  tasks:
#  - name: repo erweitern
#    template:
#     src: /home/pi/fusiondirectory.j2
#     dest: /etc/yum.repos.d/fusiondirectory.repo
     
#  - name: repo 2 erweitern
#    template:
#     src: /home/pi/fusiondirectory-extra.j2
#     dest: /etc/yum.repos.d/fusiondirectory-extra.repo
       
  - name: notwendige tools installieren
    yum: state=latest name={{ item }}
    with_items: 
    - zlib-devel 
    - bzip2-devel 
    - openssl 
    - openssl-devel 
    - ncurses-devel 
    - sqlite-devel 
    - readline-devel 
    - tk-devel 
    - gdbm-devel 
    - libpcap-devel 
    - xz-devel 
    - git 
    - libpng 
    - libjpeg 
    - libXext 
    - curl 
    - xorg-x11-font-utils 
    - fontconfig 
    - python-virtualenv 
    - libevent-devel 
    - libxml2-devel 
    - libxslt-devel 
    - openldap-devel 
    - openjpeg-devel 
    - freetype-devel 
    - libjpeg-turbo-devel 
    - libtiff-devel 
    - kernel-devel 
    - wkhtmltopdf
    - python-pip
    - postgresql-devel
#    - fusiondirectory
#    - fusiondirectory-schema
#    - schema2ldif
   
  - name: DB User anlegen
    postgresql_user:
     name: "{{ dbuser }}"
     password: "{{ dbuser_pw }}"
     state: present
     role_attr_flags: NOSUPERUSER,NOCREATEROLE,CREATEDB
    become: true
    become_user: postgres
  
  - name: user anlegen
    user:
     name: "{{ dbuser }}"
     password: "{{ dbuser_pw }}"
     home: /opt/erp
     
  - name: Log Ordner anlegen
    file:
     path: /var/log/odoo
     state: directory
     owner: "{{ dbuser }}"
     group: root

  - name: addons2 Ordner anlegen
    file:
     path: /opt/erp/addons2
     state: directory
     owner: "{{ dbuser }}"
     group: "{{ dbuser }}"
    
  - name: module kopieren  
    unarchive:
     src: /home/daniel/NAS/odoo/module/module.tar.gz
     dest: /opt/erp/addons2
     owner: "{{ dbuser }}"
     group: "{{ dbuser }}"
     mode: 0755

  - name: module installieren
    git:
     repo: "{{ item.url }}"
     version: "{{ version }}"
     depth: 1
     dest: /opt/erp/sourcemod/{{ item.dest }}
     update: no
    with_items:
    - {dest: 'OCA_web', url: 'https://github.com/OCA/web.git'}
    - {dest: 'ingadhoc', url: 'https://github.com/ingadhoc/miscellaneous.git'}
    - {dest: 'eq', url: 'https://github.com/equitania/odoo-addons.git'}
    - {dest: 'no_phoning', url: 'https://github.com/bizzappdev/oerp_no_phoning_home.git'}
    - {dest: 'smile', url: 'https://github.com/savoirfairelinux/smile_odoo_addons.git'}
    - {dest: 'poslogo', url: 'https://github.com/muralikrishnareddy/poslogo.git'}
    become: true
    become_user: "{{ dbuser }}"
  
  - name: odoo per github installieren 
    git:
     repo: 'https://github.com/odoo/odoo.git'
     version: "{{ version }}"
     depth: 1
     dest: /opt/erp/odoo
     update: yes
   # command:  git clone https://www.github.com/odoo/odoo --depth 1 --branch 8.0 --single-branch  
    become: true
    become_user: "{{ dbuser }}"

  - name: python Anhängigkeiten installieren
    command: pip install -r /opt/erp/odoo/requirements.txt
    
  - name: configfile kopieren
    template:
     src: /home/daniel/NAS/odoo/odoo-server.j2
     dest: /etc/odoo-server.conf
     
  - name: configfile kopieren
    template:
     src: /home/daniel/NAS/odoo/odoo_service.j2
     dest: /usr/lib/systemd/system/odoo.service
  
  - name: odoo starten
    service:
     name: odoo
     state: started
     enabled: yes 
     
    
