---
- hosts: server
  remote_user: root
  roles:
  - { role: sfromm.postgresql }
    
  tasks:
  - name: repo erweitern
    template:
     src: /home/pi/fusiondirectory.j2
     dest: /etc/yum.repos.d/fusiondirectory.repo
     
  - name: repo 2 erweitern
    template:
     src: /home/pi/fusiondirectory-extra.j2
     dest: /etc/yum.repos.d/fusiondirectory-extra.repo
       
  - name: notwendige tools installieren
    yum: state=present name={{ item }}
    with_items: 
    - zlib-devel 
    - bzip2-devel 
    - openssl 
    - openssl-devel 
    - ncurses-devel 
    - sqlite-devel 
    - readline-devel 
    - tk-devel 
    - gdbm-devel 
    - libpcap-devel 
    - xz-devel 
    - git 
    - libpng 
    - libjpeg 
    - libXext 
    - curl 
    - xorg-x11-font-utils 
    - fontconfig 
    - python-virtualenv 
    - libevent-devel 
    - libxml2-devel 
    - libxslt-devel 
    - openldap-devel 
    - openjpeg-devel 
    - freetype-devel 
    - libjpeg-turbo-devel 
    - libtiff-devel 
    - kernel-devel 
    - wkhtmltopdf
    - python-pip
    - postgresql-devel
   
  - name: DB User anlegen
    postgresql_user:
     name: "{{ dbuser }}"
     password: "{{ dbuser_pw }}"
     state: present
     role_attr_flags: NOSUPERUSER,NOCREATEROLE,CREATEDB
    become: true
    become_user: postgres
  
  - name: user anlegen
    user:
     name: "{{ dbuser }}"
     password: "{{ dbuser_pw }}"
     home: /opt/odoo

#  - name: odoo per github installieren 
#    command:  git clone https://www.github.com/odoo/odoo --depth 1 --branch 8.0 --single-branch  
#    become: true
#    become_user: "{{ dbuser }}"

#  - name: python Anhängigkeiten installieren
#    command: pip install -r /opt/odoo/odoo/requirements.txt
    
  - name: configfile kopieren
    template:
     src: /home/pi/odoo-server.j2
     dest: /etc/odoo-server.conf
     
  - name: configfile kopieren
    template:
     src: /home/pi/odoo_service.j2
     dest: /usr/lib/systemd/system/odoo.service
  
  - name: odoo starten
    service:
    name: odoo
    state: started
    enabled: yes 
     
    
