---
- hosts: server
  remote_user: root
  
  tasks:
  - name: lookup of a cvs file
    debug: msg="{{ lookup('csvfile','user file=/home/daniel/NAS/odoo/ldapuser_template.csv delimiter=,') }}"
    register: user_out
    
  - name: User anlegen
    ldap_entry:
      dn: "uid={{ lookup('csvfile', item + ' file=/home/daniel/NAS/odoo/ldapuser_template.csv col=4 delimiter=,') }},{{ ldap_user_dn }}"
      objectClass:
        - inetOrgPerson
      attributes:
        cn: "{{ lookup('csvfile', item + ' file=/home/daniel/NAS/odoo/ldapuser_template.csv col=1 delimiter=,') }}"
        sn: "{{ lookup('csvfile', item + ' file=/home/daniel/NAS/odoo/ldapuser_template.csv col=3 delimiter=,') }}"
        givenName: "{{ lookup('csvfile', item + ' file=/home/daniel/NAS/odoo/ldapuser_template.csv col=2 delimiter=,') }}"
        uid: "{{ lookup('csvfile', item + ' file=/home/daniel/NAS/odoo/ldapuser_template.csv col=4 delimiter=,') }}"
        userPassword: "{{ lookup('csvfile', item + ' file=/home/daniel/NAS/odoo/ldapuser_template.csv col=4 delimiter=,') }}"   
      server_uri: ldap://localhost/
      bind_dn: "{{ bind_dn }}"
      bind_pw: "{{ bind_pw }}"
      state: present
      with_item:  "{{ user_out.stdout_lines }}"
 
#  - name: Gruppe anlegen
#    ldap_entry:
#      dn: "cn={{ ldap_kd_gruppe }},{{ ldap_gruppe_dn }}"
#      objectClass:
#        - groupOfNames
#      attributes:
#        cn: "{{ ldap_kd_gruppe }}"
#        member: "uid={{ ldap_uid }},{{ ldap_user_dn }}"
#      server_uri: ldap://localhost/
#      bind_dn: "{{ bind_dn }}"
#      bind_pw: "{{ bind_pw }}"
#      state: present
