
---
- hosts: server
  remote_user: root

  tasks:
  - name: User anlegen
    ldap_entry:
      dn: "uid={{ ldap_uid }},{{ ldap_user_dn }}"
      objectClass:
        - inetOrgPerson
      attributes:
        cn: "{{ ldap_cn }}"
        sn: "{{ ldap_nachname }}"
        givenName: "{{ ldap_vorname}}"
        uid: "{{ ldap_uid }}"
        userPassword: "{{ userPassword }}"    
    server_uri: ldap://localhost/
    bind_dn: "{{ bind_dn }}"
    bind_pw: "{{ bind_pw }}"
    state: present
 
