---
- hosts: server
  remote_user: root
  
  roles:
  - role: mkouhei.include_csv
  
  tasks:
  - copy: 
      src: /home/daniel/NAS/odoo/ldapuser_template.csv
      dest: /root/ldapuser_template.csv
    
  - include_csv: src=/root/ldapuser_template.csv delimiter=","
  
#  - debug: msg="{{item.id}}"
#    with_items: "{{ldapuser_template}}" 
  
  - name: User anlegen
    ldap_entry:
      dn: "uid={{ item.ldap_uid }},{{ item.ldap_user_dn }}"
      objectClass:
        - inetOrgPerson
      attributes:
        cn: "{{ item.ldap_cn }}"
        sn: "{{ item.ldap_nachname }}"
        givenName: "{{ item.ldap_vorname }}"
        uid: "{{ item.ldap_uid }}"
        userPassword: "{{ item.userPassword }}"    
      server_uri: ldap://localhost/
      bind_dn: "{{ item.bind_dn }}"
      bind_pw: "{{ item.bind_pw }}"
      state: present
    with_items: "{{ldapuser_template}}"
      
 
  - name: Gruppe anlegen
    ldap_entry:
      dn: "cn={{ item.ldap_kd_gruppe }},{{ item.ldap_gruppe_dn }}"
      objectClass:
        - groupOfNames
      attributes:
        cn: "{{ item.ldap_kd_gruppe }}"
        member: "uid={{ item.ldap_uid }},{{ item.ldap_user_dn }}"
      server_uri: ldap://localhost/
      bind_dn: "{{ item.bind_dn }}"
      bind_pw: "{{ item.bind_pw }}"
      state: present
    with_items: "{{ldapuser_template}}"
    
  - name: User der neuen Gruppe hinzufügen
    ldap_attr:
      dn: "cn={{ item.ldap_kd_gruppe }},{{ item.ldap_gruppe_dn }}"
      name: member
      values: "uid={{ item.ldap_uid }},{{ item.ldap_user_dn }}"
      server_uri: ldap://localhost/
      bind_dn: "{{ item.bind_dn }}"
      bind_pw: "{{ item.bind_pw }}"
      state: present
    with_items: "{{ldapuser_template}}"
