---
- hosts: windows

  tasks:
  - name: Drucker anlegen
    win_shell: add-printer -name "Testdrucker" -drivername "P-4035i MFP KX" -port "192.168.178.22" -Published -Shared -ShareName "Testdrucker"
   # yum: state=latest name={{ item }}
   # with_items:
   # - epel-release
