---
- hosts: windows

  tasks:
  - name: Drucker anlegen
    win_shell: add-printer -name "D_Büro_P4035i_SW" -drivername "P-4035i MFP KX" -port "192.168.178.22" -Published -Shared -ShareName "D_Büro
    _P4035i_SW"
   # yum: state=latest name={{ item }}
   # with_items:
   # - epel-release
