---
- hosts: AD
  
  tasks:
  
  - name: get content
    win_shell: Get-Content {{ pfad }}
    register: userimport_out

  - name: Ensure users are present with address information
    win_domain_user:
      name: "{{ lookup('csvfile', item + ' file=userimport.csv col=0 delimiter=;') }}"
      firstname: "{{ lookup('csvfile', item + ' file=userimport.csv col=1 delimiter=;') }}"
      surname: "{{ lookup('csvfile', item + ' file=userimport.csv col=2 delimiter=;') }}"
      email: "{{ lookup('csvfile', item + ' file=userimport.csv col=3 delimiter=;') }}"
      company: "{{ lookup('csvfile', item + ' file=userimport.csv col=9 delimiter=;') }}"
      password: "Start123!"
      state: present
#      groups:
#        - Domain Admins
#      street: {{ lookup('csvfile', item + ' file=userimport.csv col=6 delimiter=;') }}
#      city: {{ lookup('csvfile', item + ' file=userimport.csv col=5 delimiter=;') }}
#      postal_code: {{ lookup('csvfile', item + ' file=userimport.csv col=4 delimiter=;') }}
    with_items: "{{ userimport_out.stdout_lines }}"
#    with_lines: Get-Content {{ pfad }}
#    ignore_errors: True
